Some more minor fixups to bootstrap and provisioning. wwstatus is no longer required as wwlogger has superceeded it.
git-svn-id: https://warewulf.lbl.gov/svn/trunk@923 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/provision/initramfs/capabilities/transport-http/wwgetvnfs b/provision/initramfs/capabilities/transport-http/wwgetvnfs
--- a/provision/initramfs/capabilities/transport-http/wwgetvnfs
+++ b/provision/initramfs/capabilities/transport-http/wwgetvnfs
@@ -15,7 +15,12 @@ cd ${NEWROOT:-/}
 
 while true; do
     for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do
-        if wget -q -O - "http://$master/WW/vnfs?hwaddr=$HWADDR" 2>/dev/null | gunzip 2>/dev/null | cpio -uid --quiet 2>/dev/null; then
+        # This pipeline always returns true. Would be super nice to check for return value of
+        # wget without disrupting the pipeline! Please... somoene... fixme!
+        wget -q -O - "http://$master/WW/vnfs?hwaddr=$HWADDR" 2>/dev/null | gunzip 2>/dev/null | cpio -uid --quiet 2>/dev/null
+
+        # This is a cheesy way to see if the above wget worked... Ewww, I know. Please FIXME!
+        if [ -f "$NEWROOT/sbin/init" ]; then
             exit 0
         fi
     done
@@ -23,3 +28,4 @@ while true; do
     throttled_sleep
 done
 
+exit 1
