This fixes a release showstopper bug that was identified by John Hanks and replicated by Karen Fernsler. In a nutshell, wwlogger was deadlocking certain points of the provisioning process. Fix was to move to proper syslogd implementation on the nodes.
git-svn-id: https://warewulf.lbl.gov/svn/trunk@984 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/provision/initramfs/wwlogger b/provision/initramfs/wwlogger
--- a/provision/initramfs/wwlogger
+++ b/provision/initramfs/wwlogger
@@ -7,8 +7,10 @@
 # required approvals from the U.S. Dept. of Energy).  All rights reserved.
 #
 
-. /warewulf/transports/http/functions
-
-for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do
-    echo "<6>$WWNAME wwbootstrap: $1" | nc -w 0 -u $master 514 2>/dev/null
-done
+if [ -n "$1" ]; then
+    if ! logger -t wwlogger "$1"; then
+        echo "Failed to spawn logger" >&2
+    fi
+else
+    echo "USAGE: wwlogger 'message to send'"
+fi
