Bunch of changes across the board: - Show "skipped" message on bootup for provision modules that exit 1 - wwbootstrap imports directly into Warewulf if --file is not passed - wwvnfs also imports directly into Warewulf if --file is not passed - Additional cleanups and fixes
git-svn-id: https://warewulf.lbl.gov/svn/trunk@482 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/provision/initramfs/capabilities/setup-filesystems/80-mkbootable b/provision/initramfs/capabilities/setup-filesystems/80-mkbootable
--- a/provision/initramfs/capabilities/setup-filesystems/80-mkbootable
+++ b/provision/initramfs/capabilities/setup-filesystems/80-mkbootable
@@ -54,9 +54,28 @@ if [ -n "$WWBOOTLOADER" -a -f "/tmp/rootdev" ]; then
                     mkdir $NEWROOT/dev/mapper
                     mknod $NEWROOT/dev/mapper/control c 10 58
 
-                    chroot $NEWROOT /sbin/grub-install $WWBOOTLOADER >/dev/null
+                    if chroot $NEWROOT /sbin/grub-install $WWBOOTLOADER >/dev/null; then
+                        exit 0
+                    else
+                        echo "Running grub-install failed!"
+                        exit 255
+                    fi
+                else
+                    echo "Could not find INITRD and/or KERNEL version!"
+                    exit 2
                 fi
+            else
+                echo "GRUB is not installed!"
+                exit 2
             fi
+        else
+            echo "Could not identify kernel version in VNFS!"
+            exit 2
         fi
+    else
+        echo "BOOTLOADER=$BOOTLOADER is invalid!"
+        exit 2
     fi
+else
+    exit 1
 fi
