Various fixups to wwinit:     * Move required sanity into wwinit itself     * Create a function for user checking     * Add user checking on a per module basis     * Changed wwtest to not assume its a test command
git-svn-id: https://warewulf.lbl.gov/svn/trunk@1098 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/common/bin/wwinit b/common/bin/wwinit
--- a/common/bin/wwinit
+++ b/common/bin/wwinit
@@ -14,6 +14,10 @@ if ! which wwconfig >/dev/null 2>&1; then
     exit 255
 fi
 
+if ! which wwsh >/dev/null 2>&1; then
+    echo "ERROR: wwsh is not in path!"
+    exit 255
+fi
 
 eval `wwconfig -sea`
 
@@ -82,7 +86,9 @@ shift $((OPTIND-1))
 
 if [ -z "$1" ]; then
     usage
+    exit
 fi
+
 
 for init in $@; do
     test -n "$VERBOSE" && echo "VERBOSE:  Running init: $init"
