Lots of updates trying to get wwmkchroot going for 3.2 release
git-svn-id: https://warewulf.lbl.gov/svn/trunk@914 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/vnfs/bin/wwmkchroot.in b/vnfs/bin/wwmkchroot.in
--- a/vnfs/bin/wwmkchroot.in
+++ b/vnfs/bin/wwmkchroot.in
@@ -7,9 +7,11 @@
 # through Lawrence Berkeley National Laboratory (subject to receipt of any
 # required approvals from the U.S. Dept. of Energy).  All rights reserved.
 #
-# $Id$
+# $Id: wwmkchroot 913 2012-04-19 00:33:31Z gmk $
 
-SYSCONFDIR=$(wwconfig SYSCONFDIR)
+prefix="@prefix@"
+exec_prefix="@exec_prefix@"
+libexecdir="@libexecdir@"
 
 usage() {
     echo "$0 [options] TEMPLATE_NAME PATH"
@@ -19,13 +21,17 @@ usage() {
     echo "    -h        Usage summary"
     echo
     echo "TEMPLATE_NAME (select one of the following):"
-    for i in $SYSCONFDIR/warewulf/wwmkchroot/*.tmpl; do
+    for i in $libexecdir/warewulf/wwmkchroot/*.tmpl; do
         NAME=`basename $i | sed -e 's/\.tmpl$//'`
         echo "   $NAME"
     done
     echo
     echo "PATH:"
     echo "   This is the location where the VNFS will be created"
+    echo
+    echo "EXAMPLES:"
+    echo
+    echo " # wwmkchroot rhel-6 /var/chroots/rhel-6"
     echo
 }
 
@@ -57,30 +63,33 @@ shift
 export VNFSDIR=$1
 shift
 
+if [ -z "$VNFSTEMPLATE" -o -z "$VNFSDIR" ]; then
+    usage
+    exit 1
+fi
+
 
 #### Loading templates
 test -n "$VERBOSE" && echo "Loading general template"
-if [ -f "$SYSCONFDIR/warewulf/wwmkchroot.tmpl" ]; then
-    . "$SYSCONFDIR/warewulf/wwmkchroot.tmpl"
-    TMPL1_FUNCTIONS=$FUNCTIONS
+if [ -f "$libexecdir/warewulf/wwmkchroot.tmpl" ]; then
+    . "$libexecdir/warewulf/wwmkchroot.tmpl"
 else
-    echo "$0: Error: Can not find $SYSCONFDIR/warewulf/wwmkchroot.tmpl"
+    echo "$0: Error: Can not find $libexecdir/warewulf/wwmkchroot.tmpl"
     exit 1;
 fi
 
 test -n "$VERBOSE" && echo "Loading $VNFSTEMPLATE template"
-if [ -f "$SYSCONFDIR/warewulf/wwmkchroot/$VNFSTEMPLATE.tmpl" ]; then
-    . "$SYSCONFDIR/warewulf/wwmkchroot/$VNFSTEMPLATE.tmpl"
-    TMPL2_FUNCTIONS=$FUNCTIONS
+if [ -f "$libexecdir/warewulf/wwmkchroot/$VNFSTEMPLATE.tmpl" ]; then
+    . "$libexecdir/warewulf/wwmkchroot/$VNFSTEMPLATE.tmpl"
 else
-    echo "$0: Error: Can not find $SYSCONFDIR/warewulf/wwmkchroot/$VNFSTEMPLATE.tmpl"
+    echo "$0: Error: Can not find $libexecdir/warewulf/wwmkchroot/$VNFSTEMPLATE.tmpl"
     exit 1
 fi
 
 
 #### Running template functions
 test -n "$VERBOSE" && echo "Starting template functions"
-for function in $TMPL1_FUNCTIONS $TMPL2_FUNCTIONS; do
+for function in $FUNCTIONS; do
     test -n "$VERBOSE" && echo "Running: $function"
     $function || exit 1
 done
diff --git a/vnfs/libexec/wwmkchroot/rhel-generic.tmpl b/vnfs/libexec/wwmkchroot/rhel-generic.tmpl
--- a/vnfs/libexec/wwmkchroot/rhel-generic.tmpl
+++ b/vnfs/libexec/wwmkchroot/rhel-generic.tmpl
@@ -1,11 +1,3 @@
-# -*-Shell-script-*-
-# 
-# wwmkchroot file for Red Hat based distributions
-#
-# Based off original mkchroot-rh.sh
-
-DESC="Red Hat based distributions"
-VERSION=`rpm -qf /etc/redhat-release  --qf '%{VERSION}\n'`
 
 PKGLIST="SysVinit basesystem bash redhat-release chkconfig coreutils e2fsprogs \
     ethtool filesystem findutils gawk grep initscripts iproute iputils \
@@ -15,30 +7,37 @@ PKGLIST="SysVinit basesystem bash redhat-release chkconfig coreutils e2fsprogs \
     openssh-clients openssh-server passwd dhclient pciutils vim-minimal \
     shadow-utils strace vixie-cron cronie crontabs"
 
-build_vnfs()
-{
 
-    echo "Creating yum configuration based on master"
+
+sanity_check() {
+    if ! rpm -q yum >/dev/null 2>&1; then
+        echo "ERROR: Could not query RPM for YUM"
+        return 1
+    fi
+    return 0
+}
+
+buildchroot() {
+
+    VERSION=`rpm -qf /etc/redhat-release  --qf '%{VERSION}\n'`
+
+    mkdir -p $VNFSDIR/etc
+
     cp -rap /etc/yum.conf /etc/yum.repos.d $VNFSDIR/etc
     sed -i -e "s/\$releasever/$VERSION/g" `find $VNFSDIR/etc/yum* -type f`
 
-    echo "Starting package installation"
     yum --tolerant --installroot $VNFSDIR -y install $PKGLIST
 
     if [ $? -ne 0 ]; then
         echo "ERROR: Failed to create chroot"
-        exit 1
+        return 1
     fi
 
-    vnfs_generate_fstab 
+    return 0
+}
 
-    echo "NETWORKING=yes" > $VNFSDIR/etc/sysconfig/network
-
-    vnfs_generate_ssh 
-
-    vnfs_setup_auth 
-
+postconfig() {
     touch $VNFSDIR/fastboot
-
+    return 0
 }
 
