Saving work in progress of stateful provisioning.
git-svn-id: https://warewulf.lbl.gov/svn/trunk@374 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/provision/initramfs/capabilities/provision-localdisk/10-sanitycheck b/provision/initramfs/capabilities/provision-localdisk/10-sanitycheck
--- a/provision/initramfs/capabilities/provision-localdisk/10-sanitycheck
+++ b/provision/initramfs/capabilities/provision-localdisk/10-sanitycheck
@@ -8,17 +8,11 @@
 #
 
 
-if [ -n "$WWDEVDISK" ]; then
+if [ -z "$WWDEVDISK" ]; then
     WWDEVDISK=`egrep ' .da' /proc/partitions | awk '{print $4}' | head -n 1`
 fi
 
-if [ -n "$WWFILESYSTEM" ]; then
-    WWFILESYSTEM=ext2
-fi
-
-
-if [ -x "/sbin/mkfs.$WWFILESYSTEM" ]; then
-    if ! /sbin/mkfs.$WWFILESYSTEM /dev/$WWDEVDISK; then
-        exit 255
-    fi
+if [ -z "$WWDEVDISK" ]; then
+    echo "ERROR: Could not locate the hard drive to partition to!"
+    exit 255
 fi
