Fixed some minor uh-oh's.
git-svn-id: https://warewulf.lbl.gov/svn/trunk@542 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/ipmi/initramfs/10-ipmiconfig b/ipmi/initramfs/10-ipmiconfig
--- a/ipmi/initramfs/10-ipmiconfig
+++ b/ipmi/initramfs/10-ipmiconfig
@@ -7,20 +7,25 @@
 # required approvals from the U.S. Dept. of Energy).  All rights reserved.
 #
 
-modprobe ipmi_si >/dev/null 2>&1
-modprobe ipmi_devintf >/dev/null 2>&1
-
-sleep 1
-
-if [ ! -c /dev/ipmi0 -a ! -c /dev/ipmi/0 ]; then
-    echo "Kernel support not present"
-    exit 1
-fi
 
 IPMI_UID=${WWIPMI_UID:-3}
 
 
 if [ -n "$WWIPMI_IPADDR" -a -n "$WWIPMI_NETMASK" ]; then
+
+    modprobe ipmi_devintf >/dev/null 2>&1
+    if ! modprobe ipmi_si >/dev/null 2>&1; then
+        echo -ne "Hardware not supported"
+        exit 1
+    fi
+
+    sleep 1
+
+    if [ ! -c /dev/ipmi0 -a ! -c /dev/ipmi/0 ]; then
+        echo -ne "Device files not found"
+        exit 1
+    fi
+
     for channel in ${WWIPMI_LANCHANNEL:-1 2 3 4 5 6}; do
         if ipmitool lan print $channel >/dev/null 2>&1; then
             RETVAL=0
@@ -57,10 +62,10 @@ if [ -n "$WWIPMI_IPADDR" -a -n "$WWIPMI_NETMASK" ]; then
             exit $RETVAL
         fi
     done
-    echo "Interface not found"
+    echo -ne "Interface not found"
     exit 1
 else
-    echo "IPMI is not configured"
+    echo -ne "IPMI is not configured"
     exit 1
 fi
 
