Modification of wwmkchroot as a Test.
wwmkchroot will take a command line like:

  ./wwmkchroot --url cent-6 /var/chroots/cent-6-urltest

Download the 'cent-6.vnfs' image from the URL location in:

  SYSCONFDIR/warewulf/wwmkchroot/VNFS.Source

and unpack the VNFS image to chroot location.

Couple helper functions added to wwfunctions.



git-svn-id: https://warewulf.lbl.gov/svn/trunk@799 3fa55bd7-8392-0410-b022-a3fc164e7bfc

diff --git a/common/etc/wwfunctions b/common/etc/wwfunctions
--- a/common/etc/wwfunctions
+++ b/common/etc/wwfunctions
@@ -96,4 +96,49 @@ vnfs_setup_auth()
 
 }
 
+# Download VNFS
+vnfs_download()
+{
+    if [ $# -ne 1 ]; then
+        echo "ERROR: vnfs_download: Usage: vnfs_download [image]";
+        exit 1;
+    fi
+    if [ -z "$VNFSHOST" ]; then
+        echo "ERROR: vnfs_download: VNFSHOST not set.";
+        exit 1;
+    fi
+
+    ODIR=${TMP:-/tmp}
+    if which wget 2>&1 >/dev/null; then
+        wget -O ${ODIR}/$VNFSIMG $VNFSHOST/$VNFSIMG;
+    elif which curl 2>&1 >/dev/null; then
+        curl $VNFSHOST/$VNFSIMG -o ${ODIR}/$VNFSIMG;
+    else
+        echo "ERROR: vnfs_download: wget or curl not found.";
+        exit 1;
+    fi
+    printf "%s" ${ODIR}/${VNFSIMG}
+}
+
+# Build chroot structure from VNFS Image
+build_chroot()
+{
+    if [ $# -ne 2 ]; then
+        echo "ERROR: build_chroot: Usage: build_chroot [image] [directory]";
+        exit 1;
+    fi
+
+    IMG=$1;
+    DIR=$2;
+
+    echo "build_chroot: Building chroot structure in $DIR from image $IMG";
+
+    mkdir -p $DIR;
+    cd $DIR;
+    gunzip -c $IMG | cpio -H newc -di;
+    mv $IMG $(dirname $DIR);
+
+    echo "build_chroot: chroot structure created and VNFS Image moved to: $(dirname $DIR)/$(basename $IMG)";
+}
+
 # vim:filetype=sh:syntax=sh:expandtab:ts=4:sw=4:
